import { Speaker } from './models/speaker.model';

export const speakersData = [
	new Speaker('Josue Gutierrez',
		'Google Developer Expert, @AngularMexico organizer',
		'Pellentesque <a href="#">maximus</a> malesuada lectus, vel lobortis erat efficitur a. Donec ac auctor enim, at bibendum risus. Phasellus hendrerit arcu et elit sollicitudin, vel tempus nibh condimentum. Proin dolor est, faucibus sit amet commodo vel, hendrerit ut nulla. Donec vitae nisl metus. Maecenas eu dolor et ante maximus auctor nec eget elit. Phasellus eget auctor sem, vel suscipit nunc. Aenean vulputate imperdiet urna, et convallis nulla mattis ut. Fusce nisl tellus, sodales vel libero in, viverra luctus elit. Nam blandit, enim vel ultricies elementum, libero nulla mollis nunc, sed facilisis ante mauris quis ex.',
		{ twitter: 'eusoj' }, './assets/img/profiles/josue_gutierrez.jpg'),
	new Speaker('Simona Cottin',
		'Microsoft, London',
		'Simona is an enthusiastic full stack developer with experience in building rich data visualization tools for network data and more recently building apps in the cloud. Communities power her up and that´s why she is co-organising the London Javascript meetup. Passionate about knowledge sharing, she has also worked on workshops for Women Who Code in Dublin and NgGirls in Copenhagen encouraging women to learn more about programming.',
		{ twitter: 'simona_cotin' }, './assets/img/profiles/simona_cottin.jpg'),
	new Speaker('Luis Aviles',
		'Angular Bolivia Rockstar',
		'Software Developer, Angular lover, Trainer, Speaker, Photography and Astrophotography enthusiast.',
		{ twitter: 'luixaviles' }, './assets/img/profiles/luis_aviles.jpg'),
	new Speaker('Andrés Villanueva',
		'Angular + Firebase Expert',
		'Venezolano, Desarrollador Frontend, JavaScripter, fanático de metodologías ágiles y patrones de desarrollo.',
		{}, './assets/img/profiles/andres_villanueva.jpg'),
	new Speaker('Israel Guzmán',
		'Senior Software engineer • Experienced Angular & AngularJS developer',
		'Israel, comenzó a programar hace 23 años cuando tenía 12, tiene 5 años desarrollando con AngularJS y casi 2 años con Angular, desde la primer versión beta. Creó en Youtube el primer canal de AngularJS en español, fue uno de los organizadores del Meetup de Angular en la Ciudad de México, es parte del equipo de docs oficiales de Angular, así como líder de los docs oficiales en español y esta obsesionado con las nuevas tecnologías web y móviles.',
		{ twitter: 'mraatron' }, './assets/img/profiles/user5.jpg'),
	new Speaker('Minko Gechev',
		'Google Developer Expert, Co-founder & CTO at Rhyme',
		'Minko is co-founder & CTO at Rhyme with a strong passion for open source. He loves to experiment with theoretical concepts and apply them in practice. Minko teaches, speaks and writes about JavaScript, Angular and computer science. Some of the projects he works on are his book "Switching to Angular", the Angular style guide, codelyzer, angular-seed, and many others.',
		{ twitter: 'mgechev' }, './assets/img/profiles/minko_gechev.jpg'),
	new Speaker('Carlos Angulo',
		'Industrial Designer, Frontend developer and Animation Expert',
		'Industrial desinger. Frontend Developer, animator and UX-UI expert',
		{ twitter: 'carlosacns' }, './assets/img/profiles/carlos_angulo.jpg')
];
