import { Speaker } from './models/speaker.model';

export const speakersData = [
	new Speaker('Josue Gutierrez',
		'Google Developer Expert, @AngularMexico organizer',
		'@Google Developer Expert in Web Technologies • Organizer of @angularmexico • ♥ @xochalarcon • Human',
		{ twitter: 'eusoj' }, './assets/img/profiles/josue_gutierrez.jpg'),
	new Speaker('Simona Cotin [Via Hangouts]',
		'Microsoft, London',
		'Simona is an enthusiastic full stack developer with experience in building rich data visualization tools for network data and more recently building apps in the cloud. Communities power her up and that´s why she is co-organising the London Javascript meetup. Passionate about knowledge sharing, she has also worked on workshops for Women Who Code in Dublin and NgGirls in Copenhagen encouraging women to learn more about programming.',
		{ twitter: 'simona_cotin' }, './assets/img/profiles/simona_cottin.jpg'),
	new Speaker('Carlos Angulo',
		'Frontend developer, Animations Expert',
		'Industrial desinger. Frontend Developer at @YuxiGlobal, animator and UX-UI expert. ',
		{ twitter: 'carlosacns' }, './assets/img/profiles/carlos_angulo.jpg'),
	new Speaker('Luis Aviles',
		'Angular Bolivia Rockstar',
		'Software Developer, Angular lover, Trainer, Speaker, Photography and Astrophotography enthusiast.',
		{ twitter: 'luixaviles' }, './assets/img/profiles/luis_aviles.jpg'),
	new Speaker('Minko Gechev [Via Hangouts]',
		'Google Developer Expert, Co-founder & CTO at Rhyme',
		'Minko is co-founder & CTO at Rhyme with a strong passion for open source. He loves to experiment with theoretical concepts and apply them in practice. Minko teaches, speaks and writes about JavaScript, Angular and computer science. Some of the projects he works on are his book "Switching to Angular", the Angular style guide, codelyzer, angular-seed, and many others.',
		{ twitter: 'mgechev' }, './assets/img/profiles/minko_gechev.jpg'),
	new Speaker('Andrés Villanueva',
		'Angular + Firebase Expert',
		'Venezolano, Desarrollador Frontend, JavaScripter, fanático de metodologías ágiles y patrones de desarrollo.',
		{twitter: 'villanuevand' }, './assets/img/profiles/andres_villanueva.jpg'),
	new Speaker('Israel Guzmán',
		'Experienced Angular/AngularJS developer',
		'Israel\'s been programming for the past 22 years, and he\'s an experienced Angular and AngularJS Senior Developer. <br> He made the first AngularJS Youtube channel in Spanish and former Mexico City\'s Angular Meetups organizer.',
		{ twitter: 'israelgp4' }, './assets/img/profiles/israel_guzman.png'),
];
