import { Speaker } from './models/speaker.model';

export const speakersData = [
	new Speaker('Josue Gutierrez',
		'Google Developer Expert, @AngularMexico organizer',
		'@Google Developer Expert in Web Technologies • Organizer of @angularmexico • ♥ @xochalarcon • Human',
		{ twitter: 'eusoj' }, './assets/img/profiles/josue_gutierrez.jpg'),
	new Speaker('Simona Cotin [Via Hangouts]',
		'Microsoft, London',
		'Simona is an enthusiastic full stack developer with experience in building rich data visualization tools for network data and more recently building apps in the cloud. Communities power her up and that´s why she is co-organising the London Javascript meetup. Passionate about knowledge sharing, she has also worked on workshops for Women Who Code in Dublin and NgGirls in Copenhagen encouraging women to learn more about programming.',
		{ twitter: 'simona_cotin' }, './assets/img/profiles/simona_cottin.jpg'),
	new Speaker('Luis Aviles',
		'Experienced Angular Dev. @angularBolivia organizer.',
		'Luis works as a Software Engineer in AssureSoft Bolivia where he currently plays as a Lead Development Engineer of a Front-end Team, creating web applications with frameworks like Angular. He started to develop web apps with AngularJS 1.2 and he mainly works with JavaScript since then. He\'s an enthusiast of Open Source software, web technologies and communities. He is the organizer of Angular Bolivia community. He has participated in different tech events, giving technical talks, code labs and specialized training workshops. When he’s not coding, Luis is reading about astronomy, or nerding out about outer space, photography or even doing astrophotography. He also writes some technical articles in his blog: https://luixaviles.com',
		{ twitter: 'luixaviles' }, './assets/img/profiles/luis_aviles.jpg'),
	new Speaker('Carlos Angulo',
		'Frontend developer, Animations Expert',
		'Industrial desinger. Frontend Developer at @YuxiGlobal, animator and UX-UI expert. ',
		{ twitter: 'carlosacns' }, './assets/img/profiles/carlos_angulo.jpg'),
	new Speaker('Minko Gechev [Via Hangouts]',
		'Google Developer Expert, Co-founder & CTO at Rhyme',
		'Minko is co-founder & CTO at Rhyme with a strong passion for open source. He loves to experiment with theoretical concepts and apply them in practice. Minko teaches, speaks and writes about JavaScript, Angular and computer science. Some of the projects he works on are his book "Switching to Angular", the Angular style guide, codelyzer, angular-seed, and many others.',
		{ twitter: 'mgechev' }, './assets/img/profiles/minko_gechev.jpg'),
	new Speaker('Andrés Villanueva',
		'Angular + Firebase Expert',
		'Venezuelan, Frontend Developer, JavaScripter, agile metodologies and design patterns enthusiast.',
		{ twitter: 'villanuevand' }, './assets/img/profiles/andres_villanueva.jpg'),
	new Speaker('Israel Guzmán',
		'Experienced Angular/AngularJS developer',
		'Israel\'s been programming for the past 22 years, and he\'s an experienced Angular and AngularJS Senior Developer. <br> He made the first AngularJS Youtube channel in Spanish and former Mexico City\'s Angular Meetups organizer.',
		{ twitter: 'israelgp4' }, './assets/img/profiles/israel_guzman.png'),
];
